import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
import {execFileSync} from 'node:child_process';
const require=createRequire(import.meta.url),root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
let ts;try{ts=require('typescript');}catch{try{const global=execFileSync(process.platform==='win32'?'npm.cmd':'npm',['root','-g'],{encoding:'utf8'}).trim();ts=require(path.join(global,'typescript'));}catch{console.error('Для сборки исходников выполните npm ci. Готовая игра в dist не требует установки зависимостей.');process.exit(1);}}
const dev=process.argv.includes('--dev'),test=process.argv.includes('--test'),src=path.join(root,'src');
const assets=Object.fromEntries(fs.readdirSync(path.join(root,'public/assets')).filter(f=>/\.(webp|png|svg)$/.test(f)).map(f=>[f.replace(/\.[^.]+$/,''),`data:image/${f.endsWith('.svg')?'svg+xml':f.split('.').pop()};base64,${fs.readFileSync(path.join(root,'public/assets',f)).toString('base64')}`]));
const opts={target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,allowJs:true,removeComments:true,esModuleInterop:true};
function walk(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(dir,e.name)):[path.join(dir,e.name)]);}
if(test){const dest=path.join(root,'.test-build');for(const file of walk(src).filter(f=>f.endsWith('.ts')&&!f.endsWith('.d.ts'))){const output=path.join(dest,path.relative(src,file)).replace(/\.ts$/,'.js');fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,ts.transpileModule(fs.readFileSync(file,'utf8').replace(/\b__DEV__\b/g,'true').replace(/\b__ASSETS__\b/g,JSON.stringify(assets)),{compilerOptions:{...opts,module:ts.ModuleKind.ES2022},fileName:file}).outputText);}console.log(`Test modules compiled with TypeScript ${ts.version}.`);process.exit(0);}
const modules=new Map();
function resolve(from,request){if(!request.startsWith('.'))throw new Error(`Non-local runtime dependency: ${request}`);let file=path.resolve(path.dirname(from),request);if(!fs.existsSync(file)&&file.endsWith('.js'))file=file.slice(0,-3)+'.ts';if(!fs.existsSync(file))throw new Error(`Missing module: ${file}`);return file;}
function compile(file){if(modules.has(file))return modules.get(file).id;const entry={id:modules.size,code:''};modules.set(file,entry);const source=fs.readFileSync(file,'utf8').replace(/\b__DEV__\b/g,dev?'true':'false').replace(/\b__ASSETS__\b/g,JSON.stringify(assets));const result=ts.transpileModule(source,{compilerOptions:opts,fileName:file});entry.code=result.outputText.replace(/\brequire\(["']([^"']+)["']\)/g,(_,request)=>`require(${compile(resolve(file,request))})`);return entry.id;}
const entry=compile(path.join(src,'main.ts'));
const license=fs.readFileSync(path.join(src,'vendor/LICENSE.three.txt'),'utf8');
const bundle=`/* ISOBARA ${JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8')).version}\nThree.js vendored locally.\n${license}\n*/\n(()=>{'use strict';const modules={${[...modules.values()].map(m=>`${m.id}:function(module,exports,require){\n${m.code}\n}`).join(',\n')}};const cache={};function require(id){if(cache[id])return cache[id].exports;const m=cache[id]={exports:{}};modules[id](m,m.exports,require);return m.exports;}require(${entry});})();`;
const dest=path.join(root,dev?'dev-dist':'dist');fs.mkdirSync(dest,{recursive:true});const css=fs.readFileSync(path.join(src,'ui/style.css'),'utf8');
const head=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#152b2b"><meta name="description" content="ИЗОБАРА — Последний сад погоды. Одиночная 3D action-RPG с процедурным миром и портальными экспедициями."><title>ИЗОБАРА · Последний сад погоды</title><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 48 48'%3E%3Crect width='48' height='48' rx='10' fill='%23162d2e'/%3E%3Ccircle cx='24' cy='24' r='15' fill='none' stroke='%23e0c794' stroke-width='3'/%3E%3Cpath d='M24 5v10m0 18v10M5 24h10m18 0h10' stroke='%2389d6c3' stroke-width='2'/%3E%3Ccircle cx='24' cy='24' r='5' fill='%2389d6c3'/%3E%3C/svg%3E">`;
const body=`</head><body><div id="viewport"></div><div id="ui"></div><div id="loading"><div class="loader-mark">◎</div><b>ИЗОБАРА</b><span>Собираем завтрашнюю погоду…</span></div><noscript>Включите JavaScript для запуска игры.</noscript>`;
fs.writeFileSync(path.join(dest,'game.js'),bundle);fs.writeFileSync(path.join(dest,'style.css'),css);fs.writeFileSync(path.join(dest,'index.html'),head+'<link rel="stylesheet" href="./style.css">'+body+'<script src="./game.js"></script></body></html>');
fs.writeFileSync(path.join(dest,'Isobara.html'),head+'<style>'+css+'</style>'+body+'<script>'+bundle.replace(/<\/script/gi,'<\\/script')+'</script></body></html>');
console.log(`${dev?'Development':'Production'} built: ${modules.size} modules; ${(bundle.length/1048576).toFixed(2)} MiB, ${Object.keys(assets).length} local images. TypeScript ${ts.version}.`);
